version: "3.9"
services:
  auth-test:
    build:
      context: .
      target: test
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://app:secret@authdb:5432/test_authdb
      RABBITMQ_URL: amqp://rabbitmq:5672
      RUN_MODE: "test"
      ACCESS_SECRET: "testsecret"
      REFRESH_SECRET: "testrefresh"
      SKIP_BROKER: "true"
    depends_on:
      authdb:
        condition: service_healthy
    command: ["sh", "-c", "npm run lint && npm run test:run"]


  authdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_authdb
    ports:
      - "5544:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d test_authdb"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  

