version: "3.9"
services:
  user-test:
    build:
      context: .
      target: test
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://app:secret@userdb:5432/test_userdb
      RUN_MODE: "test"
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      userdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["sh", "-c", "npm run lint && npm run test:run"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI (optional)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  userdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_userdb
    ports:
      - "5544:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d test_userdb"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  

